version: "3.7"

services:

  cyberdevice:
    build:
      context: .
      dockerfile: Dockerfile
    image: cyberdevice:latest
    volumes:
      - ./_/settings.py:/cyberdevice/_/settings.py
      - ./data:/cyberdevice/data
    #ports:
    #  - 5000:5000
    #  - 5566:5566
    networks:
      - iottalk-iottalk_iottalk-net
    #environment:
    command: sh -c "python manage.py migrate && python manage.py runserver 0:8000" #tail -f /dev/null

# volumes:

networks:
  iottalk-iottalk_iottalk-net:
    external: true
